#ifndef ENV_H
#define ENV_H

// Environment
#define SIDE 20
#define ROWS SIDE
#define COLS SIDE
#define SIZE ROWS*COLS
#define RANDOM_START 1

// Rewards
#define START 0
#define STEP  -2
#define FOOD  5
#define TRAP  -20
#define END   100

class Env {
  public:
    int startRewards[SIZE] = {STEP,FOOD,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,TRAP,STEP,TRAP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,TRAP,TRAP,STEP,STEP,STEP,FOOD,TRAP,STEP,STEP,STEP,STEP,TRAP,TRAP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,FOOD,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,FOOD,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,FOOD,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,TRAP,STEP,TRAP,TRAP,STEP,FOOD,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,FOOD,STEP,STEP,STEP,STEP,FOOD,STEP,STEP,STEP,STEP,STEP,STEP,FOOD,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,TRAP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,FOOD,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,TRAP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,TRAP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,TRAP,FOOD,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,TRAP,TRAP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,FOOD,STEP,STEP,FOOD,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,FOOD,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,FOOD,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,TRAP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,STEP,END};
    int actions[SIZE][4];
    int avail_actions[SIZE][4];
    int rewards[SIZE];
    int state = 0;
    int reward = 0;
    int energy = 0;
    bool done = false;

    Env(void);
    void consume_reward(int s);
    int reset(bool random_start);
    void step(int a);
    void debug();
};

#endif